#!/bin/bash

# rm install

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Permission denied. Run as sudo!"
    exit
fi

dir=$1

sudo echo "[Unit]
Description=Refresh Prayer Times
After=network.target
After=systemd-user-sessions.service
After=network-online.target

[Service]
User=hllvc
ExecStart=/usr/local/bin/prayer-times
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/prayer-times.service

bash scripts/prayer-times

sudo mv $dir/scripts/prayer-times /usr/local/bin/prayer-times

sudo chmod 744 /usr/local/bin/prayer-times
sudo chmod 664 /etc/systemd/system/prayer-times.service

sudo systemctl daemon-reload

sudo systemctl enable prayer-times.service

sudo systemctl start prayer-times.service