#!/bin/bash

dir=/home/$USER/.config/PrayerTimes/

icon=$dir/icon/1200x630wa.png
time=$(cat $dir/data/prayer-fajr)
date=$(cat $dir/data/prayer-date)
mode=$(cat $dir/scripts/prayers-setup/mode)

if [ "$mode" == "ramdan" ]
then
    notify-send --icon=$icon "20 minuta do kraja sehura" "Kraj sehura u $time \t\t\t\t\t\t\t\t\t      ($date)"
else
    notify-send --icon=$icon "20 minuta do sabaha" "Sabah u $time \t\t\t\t\t\t\t\t\t      ($date)"
fi
    paplay $dir/sound/alarm.oga