#!/bin/bash

dir=/home/$USER/.config/PrayerTimes/

icon=$dir/icon/1200x630wa.png
time=$(cat $dir/data/prayer-zuhr)
date=$(cat $dir/data/prayer-isha)

notify-send --icon=$icon "20 minuta do jacije" "Jacija u $time \t\t\t\t\t\t\t\t\t      ($date)"
paplay $dir/sound/alarm.oga