#!/bin/bash

dir=/home/$USER/.config/PrayerTimes
name=$1
time=$2
mode=`cat $dir/scripts/prayers-setup/mode`
prayerHour=`echo $time | awk '{split($0, array, ":")} END{print array[1]}'`
prayerMinute=`echo $time | awk '{split($0, array, ":")} END{print array[2]}'`
icon=$dir/icon/1200x630wa.png
prayerTime=`cat $dir/data/prayer-$name`
date=`cat $dir/data/prayer-date`

case $name in

    "dawn")
        if [ "$mode" == "ramadan" ]
        then 
            name1="kraja sehura"
            name2="Kraj sehura"
        else
            name1=zore
            name2=Zora
        fi
        ;;

    "fajr")
        name1="izlaska sunca"
        name2="Izlazak sunca"
        ;;

    "zuhr")
        name1=podne
        name2=Podne
        ;;
    
    "asr")
        name1=ikindije
        name2=Ikindija
        ;;

    "maghrib")
        if [ "$mode" == "ramdan"]
        then
            name1=iftara
            name2=iftar
        else
            name1=akšama
            name2=Akšam
        fi
        ;;

    "isha")
        name1=jacije
        name2=Jacija
        ;;

esac

if (( $prayerMinute >= 2 && $prayerMinute <= 4 || $prayerMinute >=22 && $prayerMinute <= 24 || $prayerMinute >=32 && $prayerMinute <= 34 || $prayerMinute >=42 && $prayerMinute <= 44 || $prayerMinute >=52 && $prayerMinute <= 54))
then
    minuteWord=minute
else
    minuteWord=minuta
fi

if (( $prayerHour < 1 ))
then
    notify-send --icon=$icon "$prayerMinute $minuteWord do $name1" "$name2 u $prayerTime \t\t\t\t\t\t\t\t\      ($date)"
elif (( $prayerHour == 1 || $prayerHour == 21 ))
then
    notify-send --icon=$icon "$prayerHour sat i $prayerMinute $minuteWord do $name1" "$name2 u $prayerTime \t\t\t\t\t\t\t\t\      ($date)"
elif (( $prayerHour >= 2 && $prayerHour <= 4 || $prayerHour >= 22 && $prayerHour <= 24 ))
then
    notify-send --icon=$icon "$prayerHour sata i $prayerMinute $minuteWord do $name1" "$name2 u $prayerTime \t\t\t\t\t\t\t\t\      ($date)"
else
    notify-send --icon=$icon "$prayerHour sati i $prayerMinute $minuteWord do $name1" "$name2 u $prayerTime \t\t\t\t\t\t\t\t\      ($date)"
fi
