#!/bin/bash

arg=$1

dir=/home/$USER/.config/PrayerTimes
python $dir/python/load_prayer_times.py $USER

# loading current time
nowHour=`date '+%H'`
nowHour=`echo $nowHour | awk '{print $1 + 0}'`
nowMinutes=`date '+%M'`
nowMinutes=`echo $nowMinutes | awk '{print $1 + 0}'`
allNowMinutes=$((nowMinutes + nowHour*60))

# array of all prayer times
prayersList=(dawn fajr zuhr asr maghrib isha)

for i in {0..5}
do

    # reading names and time of prayers
    name=${prayersList[i]}
    data=`cat $dir/data/prayer-$name`

    # spliting time to hours and minutes and converting all to minutes
    prayerHour=`echo $data | awk '{split($0, array, ":")} END{print array[1]}'`
    prayerHour=`echo $prayerHour | awk '{print $1 + 0}'`
    prayerMinutes=`echo $data | awk '{split($0, array, ":")} END{print array[2]}'`
    prayerMinutes=`echo $prayerMinutes | awk '{print $1 + 0}'`
    allPrayerMinutes=$((prayerMinutes + prayerHour*60))

    case $arg in

        "--help" | "-h")
            echo "HELP
            --configure     |   -c              Configure all 5 daily prayer including dawn.

            --next          |   -n              Show next upcoming prayer via notification.

            --mode-ramadan  |   -mr             Change modes. If ramadan set you will see time until iftar
            --mode-default  |   -md             and time until sehoor ends.
            "
            break
            ;;

        "--configure" | "-c")
            if [ $i -eq 0 ]
            then
                bash $dir/scripts/clean/clean-at
                at 00:01 < /usr/local/bin/prayertimes
            fi
            # scheduling notifications 20min earlier
            allPrayerMinutes=$((allPrayerMinutes - 20))
            prayerHour=$((allPrayerMinutes/60))
            prayerMinutes=$((allPrayerMinutes%60))
            time=`echo $prayerHour:$prayerMinutes`
            at $time < $dir/scripts/prayers-setup/$name
            ;;

        "--next" | "-n")
            if [ $allPrayerMinutes -gt $allNowMinutes ]
            then
                allPrayerMinutes=$((allPreyerMinutes-allNowMinutes))
                prayerHour=$((allPrayerMinutes/60))
                prayerMinutes=$((allPrayerMinutes%60))
                time=`echo $prayerHour:$prayerMinutes`
                $dir/scripts/prayers-setup/prayer-notif $name $time
                break
            else
                if [ $i -eq 4 ]
                then
                    data=`cat $dir/data/prayer-dawn`
                    prayerHour=`echo $data | awk '{split($0, array, ":")} END{print array[1]}'`
                    prayerHour=`echo $prayerHour | awk '{print $1 + 0}'`
                    prayerMinutes=`echo $data | awk '{split($0, array, ":")} END{print array[2]}'`
                    prayerMinutes=`echo $prayerMinutes | awk '{print $1 + 0}'`
                    allPrayerMinutes=$((prayerMinutes + prayerHour*60))
                    allPrayerMinutes=$((24*60-allNowMinutes+allPrayerMinutes))
                    prayerHour=$((allPrayerMinutes/60))
                    prayerMinutes=$((allPrayerMinutes%60))
                    time=`echo $prayerHour:$prayerMinutes`
                    $dir/scripts/prayers-setup/prayer-notif dawn $time
                    break
                fi
            fi
            ;;

        "--mode-ramadan" | "-mr")
            echo ramadan > $dir/scripts/prayers-setup/mode
            break
            ;;

        "--mode-default" | "-md")
            echo default > $dir/scripts/prayers-setup/mode
            break
            ;;

        *)
            echo Type --help or -h for HELP
            break
            ;;
    esac
done


