#!/bin/bash

arg=$1

dir=/home/$USER/.config/PrayerTimes
python $dir/python/load-prayer-times.py $USER

# loading current time
nowHour=`date '+%H'`
nowHour=`echo $nowHour | awk '{print $1 + 0}'`
nowMinutes=`date '+%M'`
nowMinutes=`echo $nowMinutes | awk '{print $1 + 0}'`
allNowMinutes=$((nowMinutes + nowHour*60))

# array of all prayer times
prayersList=(dawn fajr zuhr asr maghrib isha)

for i in {0..5}
do

    # reading names and time of prayers
    name=${prayersList[i]}
    data=`cat $dir/data/prayer-$name`

    # spliting time to hours and minutes and converting all to minutes
    prayerHour=`echo $data | awk '{split($0, array, ":")} END{print array[1]}'`
    prayerHour=`echo $prayerHour | awk '{print $1 + 0}'`
    prayerMinutes=`echo $data | awk '{split($0, array, ":")} END{print array[2]}'`
    prayerMinutes=`echo $prayerMinutes | awk '{print $1 + 0}'`
    allPrayerMinutes=$((prayerMinutes + prayerHour*60))

    case $arg in

        "--reconfigure")
            if [ $i -eq 0 ]
            then
                bash $dir/scripts/clean/clean-at
            fi
            # scheduling notificationsa 20min earlier
            allPrayerMinutes=$((allPrayerMinutes - 20))
            prayerHour=$((allPrayerMinutes/60))
            prayerMinutes=$((allPrayerMinutes%60))
            time=`echo $prayerHour:$prayerMinutes`
            at $time < $dir/scripts/prayers-setup/$name
            at 00:01 < /usr/local/bin/prayer-times
            ;;

        "--next")
            if [ $allPrayerMinutes -lt $allNowMinutes ]
            then
                continue
            else
                # run
            fi
    esac
done


