#!/bin/bash

dir=/home/$USER/.config/PrayerTimes/

icon=$dir/icon/1200x630wa.png
time=$(cat $dir/data/prayer_asr)
date=$(cat $dir/data/prayer_date)

notify-send --icon=$icon "20 minuta do ikindije" "Ikindija u $time \t\t\t\t\t\t\t\t      ($date)"
paplay $dir/sound/alarm.oga