#!/bin/bash

icon=/home/hllvc/Documents/Git_Repos/Vaktija_Notification/icon/1200x630wa.png
time=$(cat /home/hllvc/Documents/Git_Repos/Vaktija_Notification/data/prayer_dawn)
date=$(cat /home/hllvc/Documents/Git_Repos/Vaktija_Notification/data/prayer_date)

notify-send --icon=$icon "20 minuta do zore" "Zora u $time \t\t\t\t\t\t\t\t\t      ($date)"
paplay /home/hllvc/Documents/Git_Repos/Vaktija_Notification/sound/alarm.oga